cloudquery/plugin-sdk-python

setup.py

Otherwise libraries importing the package need to install it themselves

fix: Add pandas requirement to setup.py

---

cloudquery/sdk/internal/servers/plugin_v3/plugin.py
cloudquery/sdk/message/sync.py
cloudquery/sdk/scheduler/scheduler.py

This is what the proto expects: https://github.com/cloudquery/plugin-pb/blob/main/plugin/v3/plugin.proto#L68
Having this in another name causes confusion with gRPC (and causes the sync from cli to fail).

fix: SyncMigrateTableMessage should have the `pa.Schema` argument named as "table"

---

cloudquery/sdk/schema/table.py

As the signature isn't correct.
We could also add it as an `@abstractmethod @property` which returns a `scheduler.TableResolver`

fix: Remove resolver() from schema.Table

---

cloudquery/sdk/scheduler/scheduler.py

The previous logger was raising an exception inside an exception handler

fix: Log error on table resolver exception/error

---

cloudquery/sdk/scheduler/scheduler.py
tests/scheduler/scheduler.py

A fix for the scheduler so that migrate messages are emitted for child tables.

fix: Emit migrate messages for child relations

---

cloudquery/sdk/scheduler/scheduler.py

This fixes a data race in the scheduler that caused some child resources to be missed.
The implementation is now correct, but it could be made more efficient. The point is that we have to submit the sentinel indicating the start of the resolver before submitting the job, otherwise the job might send a "finished" signal before the "start" signal is sent, causing the counts to be equal before all resources have actually been processed.

fix: Fix race in scheduler

---

cloudquery/sdk/serve/plugin.py

The log args are not passed to this function (and this function is due to be removed soon) so let's just skip logging for now.

fix: Fix generate docs command

---

cloudquery/sdk/internal/servers/plugin_v3/plugin.py
setup.py

Goes with https://github.com/cloudquery/plugin-pb/pull/17 and https://github.com/cloudquery/plugin-pb-python/pull/14

fix(plugin-tables): Add missing `skip_dependent_tables`

---

cloudquery/sdk/internal/servers/plugin_v3/plugin.py
cloudquery/sdk/plugin/plugin.py

This is required for the cli `tables` option to work without a full spec section for the plugin.

feat: Add support for no_connection param to init

---

cloudquery/sdk/schema/table.py
tests/schema/test_table.py

We were missing support for filtering of nested tables before, as well as `skip_dependent_tables`.  This is essentially a direct port of the Go version (https://github.com/cloudquery/plugin-sdk-python/issues/28)
Closes https://github.com/cloudquery/plugin-sdk-python/issues/28

fix: Fix filter_dfs to be recursive, add support for skip_dependent_tables

---

cloudquery/sdk/internal/servers/plugin_v3/plugin.py

Same as the Go implementation, the table list should be flattened before sending it over the wire: https://github.com/cloudquery/plugin-sdk/blob/main/schema/table.go#L204

fix: Flatten tables in plugin server getTables call

---

.github/workflows/unittests.yml
.gitignore
Dockerfile
cloudquery/sdk/internal/memdb/memdb.py
cloudquery/sdk/plugin/plugin.py
cloudquery/sdk/schema/table.py
cloudquery/sdk/serve/plugin.py
cloudquery/sdk/types/json.py
cloudquery/sdk/types/uuid.py
docs/overview.md
main.py
setup.py
tests/serve/plugin.py

This is a proposal for building and packaging Dockerised Python plugins.
The plugin definition would look like this:
```python
Plugin(
"Test",
"v0.0.1",
Options(
team_name="marcel-team",
plugin_kind="source",
dockerfiles=[
Dockerfile("Dockerfile", [
BuildTarget("linux", "amd64"),
BuildTarget("linux", "arm64"),
BuildTarget("darwin", "amd64"),
BuildTarget("darwin", "arm64"),
]),
Dockerfile("Dockerfile.windows", [
BuildTarget("windows", "amd64"),
]),
]
)
)
```
Each `Dockerfile` has a list of operating systems and architectures it supports. Multiple Dockerfiles can be defined and each is built and saved as a separate tarball.
The `package` command builds each image and saves it to the `dist` directory using internal Docker commands. The `package.json` and `docs/overview.md` files are also …

feat: Add package command

---

cloudquery/sdk/serve/plugin.py

plugin-pb-go [1.15.0](https://github.com/cloudquery/plugin-pb-go/pull/196) now uses `--license` when invoking plugins, if one is set by the cli.

fix: Add --license placeholder for future use

---

setup.py

Already present on [line 6](https://github.com/cloudquery/plugin-sdk-python/blob/main/setup.py#L6)
https://github.com/cloudquery/plugin-sdk-python/blob/541e9ca6748d327a9a4f5117ee49695e0f8bb464/setup.py#L6

chore: Remove second `package_root`

---

cloudquery/sdk/internal/servers/plugin_v3/plugin.py
cloudquery/sdk/plugin/plugin.py

Closes https://github.com/cloudquery/cloudquery/issues/16505

feat: Implement `GetSpecSchema` plugin gRPC call

---

setup.py

Reverts https://github.com/cloudquery/plugin-sdk-python/pull/151
Looks like this is not an official version? Also it's blocking https://github.com/cloudquery/cloudquery/actions/runs/8509025446/job/23303751072?pr=17441#step:4:81

fix: Revert https://github.com/cloudquery/plugin-sdk-python/pull/151

---

setup.py

Reverts cloudquery/plugin-sdk-python#167
Doesn't seem like an official version

fix: Revert "fix(deps): Update dependency python-dateutil to v2.9.0.post0"

---

cloudquery/sdk/scheduler/scheduler.py

This change will allow plugin authors to see the resource that caused the exception, helping them find the underlying cause. To get this level of information, `--log-level debug` needs to be passed to the plugin server (or the CLI, depending on whether or not the plugin is run using the grpc registry)
Closes https://github.com/cloudquery/cloudquery/issues/18002

feat: Log resource when exception occurs to aid debugging

---

setup.py

This is intended to allow the Square plugin to update to the latest SDK, see https://github.com/cloudquery/cloudquery/actions/runs/9837228486/job/27154578502#step:4:89

fix: Relax python-dateutil version requirement

---

cloudquery/sdk/schema/column.py

I implemented a PoC destination plugin in Python to prove it already supports destination plugins.
It does support them, but I encountered a small bug when processing fields with no metadata. This line errors:
https://github.com/cloudquery/plugin-sdk-python/blob/b3f898ae63385e691d3a493005e8e08103789b40/cloudquery/sdk/schema/column.py#L63
By simply adding an `or {}`, that error is gone.
I was able to implement a file destination in Python and sync XKCD into it:
```bash
$ cli sync cloudquery-config                            ⏱ 15:58:33
Loading spec(s) from cloudquery-config
Starting sync for: xkcd (cloudquery/xkcd@v1.0.6) -> [file-python (grpc@localhost:7777)]
Sync completed successfully. Resources: 2970, Errors: 0, Warnings: 0, Time: 11s
```

fix: Don't error when field has no metadata.

---

cloudquery/sdk/internal/memdb/memdb.py
cloudquery/sdk/internal/servers/plugin_v3/plugin.py
cloudquery/sdk/message/__init__.py
cloudquery/sdk/message/sync.py
cloudquery/sdk/scheduler/scheduler.py
tests/internal/memdb/memdb.py
tests/serve/plugin.py

Fixes https://github.com/cloudquery/cloudquery/issues/15525, the Python equivalent of https://github.com/cloudquery/plugin-sdk/pull/2195
Most of the changes are actually to the MemDB plugin ~~(that's why tests are failing, PR in draft while I fix those)~~, as I turned it into a "real" plugin that uses the SDK scheduler so I can test this change.

feat: Report table errors from plugins via gRPC
